CREATE DATABASE IF NOT EXISTS dbVip;
USE dbVip;

CREATE TABLE IF NOT EXISTS tbVipUser (
  Uin  INT UNSIGNED NOT NULL, /* ÓÃ»§QQºÅÂë */
  Type INT UNSIGNED NOT NULL, 
  PRIMARY KEY  (Uin)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
